name: Docker Image CI

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: Donkstation/checkout@v2
    - name: Publish to Registry
      uses: Donkstation/Publish-Docker-Github-Action@master
      with:
        name: Donkstation/Donkstation
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest"
