name: Add Extra PR labels

on:
  push:
    branches:
      - master
      - Donkstation
  pull_request_target:

jobs:
  Label:
    runs-on: ubuntu-latest
    steps:
      - name: Check for conflicting PRs
        uses: Donkstation/actions-label-merge-conflict@513a24fc7dca40990863be2935e059e650728400
        with:
          dirtyLabel: "Merge Conflict"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnDirty: "This pull request has conflicts, please resolve those before the Pull Request can be reviewed."
      - name: Apply labels based on changed files
        if: github.event_name != 'push'
        uses: Donkstation/labeler@main
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
          configuration-path: .github/file_labeler.yml
